# Site settings
title: Aqua DARTS Notes

url: "https://kubilayverboom.github.io/aqua-notes/"

# Build settings
markdown: kramdown
remote_theme: sylhare/Moonwalk
color_mode: dark
plugins:
  - jekyll-feed
